FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements inside the backend folder (build context)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy entire backend code
COPY . .

# Open Django port
EXPOSE 8000

# Start gunicorn server
CMD ["gunicorn", "config.wsgi:application", "-b", "0.0.0.0:8000"]

