FROM python:3.10-slim

WORKDIR /app

# Copy requirements from current context
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the AI backend
COPY . .

EXPOSE 9000

CMD ["python", "app.py"]

