# Build Stage
FROM node:18-alpine AS build

WORKDIR /app

# Copy only package.json and package-lock.json
COPY package*.json ./

RUN npm install

# Copy rest of the frontend source
COPY . .

RUN npm run build

# Nginx Stage
FROM nginx:alpine

# Replace default Nginx config with your custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built React files
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

